[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "mathlib"
version = "0.1.0"
description = "Math utility library"
authors = [{ name = "Adrián Flores" }]
requires-python = ">=3.9"
